name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  job_id:
    runs-on: ubuntu-latest

    env:
      CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      CLOUDSDK_CORE_PROJECT: magalu-challenge
      CLOUDSDK_PROJECT: magalu-challenge
      GCLOUD_PROJECT: magalu-challenge
      GCP_PROJECT: magalu-challenge
      GOOGLE_CLOUD_PROJECT: magalu-challenge
      CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
      CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 2.1.0

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
          project_id: magalu-challenge

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Verify authentication'
        run: 'gcloud auth list'
      
      - name: 'Terraform Init'
        run: |
          cd magalu-challenge/terraform
          terraform init
        working-directory: magalu-challenge/

      - name: 'Terraform Validate'
        run: |
          cd magalu-challenge/terraform
          terraform validate
        working-directory: magalu-challenge/

      - name: 'Terraform Plan'
        run: |
          cd magalu-challenge/terraform
          terraform plan -out=tfplan
        working-directory: magalu-challenge/

      - name: 'Terraform Apply'
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd magalu-challenge/terraform
          terraform apply -auto-approve tfplan
        working-directory: magalu-challenge/

      - name: 'Deploy to GKE'
        if: success()
        run: kubectl apply -f deployment.yaml
