name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  job_id:
    runs-on: ubuntu-latest

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          project_id: magalu-challenge

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Verify authentication'
        run: 'gcloud auth list'
      
      - name: Terraform Init
        run: cd terraform && terraform init

      - name: Terraform Validate
        run: cd terraform && terraform validate

      - name: Terraform Plan
        run: cd terraform && terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: cd terraform && terraform apply -auto-approve tfplan

      - name: Deploy to GKE
        if: success()
        run: kubectl apply -f deployment.yaml
