name: Deploy to GCP 

on:
  push:
    branches:
      - main

jobs:
  job_id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
          project_id: magalu-challenge

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Install gke-gcloud-auth-plugin'
        run: gcloud components install kubectl

      - name: 'Verify gke-gcloud-auth-plugin version'
        run: gcloud version

      - name: 'Verify authentication'
        run: gcloud auth list

      ##- name: 'Debug'
        ##run: 'ls -la'
        
      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Import VPC'
        run: terraform import google_compute_network.vpc projects/magalu-challenge/global/networks/magalu-challenge-vpc 

      - name: 'Terraform Import Subnet'
        run: terraform import google_compute_subnetwork.subnet projects/magalu-challenge/regions/us-central1/subnetworks/magalu-challenge-subnet

      - name: 'Terraform Import GKE Cluster'
        run: terraform import google_container_cluster.magalu_cluster projects/magalu-challenge/locations/us-central1/clusters/magalu-challenge-gke

      - name: 'Terraform Import GKE Node Pool'
        run: terraform import google_container_node_pool.nodes_primarios projects/magalu-challenge/locations/us-central1/clusters/magalu-challenge-gke/nodePools/magalu-challenge-gke-node-pool

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        run: terraform plan -out=tfplan

      - name: 'Terraform Apply'
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      - name: 'Get GKE credentials'
        run: gcloud container clusters get-credentials magalu-challenge-gke --region us-central1 --project magalu-challenge

      - name: 'Deploy to Config Map'
        if: success()
        run: |
          kubectl apply -f configmap.yaml --validate=false

      - name: 'Deploy to GKE'
        if: success()
        run: |
          kubectl apply -f deployment.yaml --validate=false

