name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        project_id: magalu-challenge

    - name: Use gcloud CLI
      run: |
        # Comandos para implantar seu projeto no GCP, por exemplo:
        gcloud info
